server:
  port: 8080

spring:
  application:
    name: questionnaire
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/question2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  mvc:
    static-path-pattern: /**
  servlet:
    multipart:
      max-file-size: 5MB #单个文件总的最大值
      max-request-size: 10MB # 上传文件总的最大值

mybatis:
  mapperlocations: classpath:mapper/*.xml
  type-aliases-package: com.cdu.questionnaire.pojo
