server:
  port: 8080

spring:
  application:
    name: questionnaire
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://172.81.240.35:3306/question?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: jzrL468sKlAVGW%7


mybatis:
  mapperlocations: classpath:mapper/*.xml
  type-aliases-package: com.cdu.questionnaire.pojo