server:
  port: 8080

spring:
  application:
    name: questionnaire
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://172.81.240.35:3306/question2?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://121.196.145.152:3306/question?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
#    password: lmISMk0KxWZSnhvi
    # jzrL468sKlAVGW%7
    password: jzrL468sKlAVGW%7
  mvc:
    static-path-pattern: /**
  servlet:
    multipart:
      max-file-size: 5MB #单个文件总的最大值
      max-request-size: 10MB # 上传文件总的最大值

mybatis:
  mapperlocations: classpath:mapper/*.xml
  type-aliases-package: com.cdu.questionnaire.pojo