server:
  port: 8080

spring:
  application:
    name: questionnaire
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    #jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    #jdbc:mysql://116.62.202.159:3306/fiasdb?useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&characterEncoding=UTF-8&allowMultiQueries=true
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 190125

mybatis:
  mapperlocations: classpath:mapper/*.xml
  type-aliases-package: com.cdu.questionnaire.pojo